name: Node.js CI

on: [push]

env:
  TURBO_TELEMETRY_DISABLED: 1
  DO_NOT_TRACK: 1
  WRANGLER_SEND_METRICS: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "npm"
      - run: npm ci
      - run: npx turbo build test lint
